name: Terraform Plan & Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    uses: epichouse/workflow-templates/.github/workflows/terraform.yaml@main
    with:
        environment: production
        mode: deploy
        site: "london"
    secrets:
      mastertoken: ${{ secrets.MASTERTOKEN }}
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      azure_storage_account_name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      azure_storage_container_name: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}